# Generated by Django 2.2.2 on 2019-07-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_auto_20190701_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_post', models.CharField(max_length=200)),
                ('carrier_subjct', models.CharField(max_length=200)),
                ('carrier_required', models.IntegerField(default=0)),
                ('event_schl_day', models.DateTimeField(verbose_name='Date of School Event')),
                ('a', models.CharField(db_column='column1', max_length=40)),
                ('column2', models.CharField(max_length=50)),
            ],
        ),
    ]
