# Generated by Django 2.2.2 on 2019-07-01 05:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='column3',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='column4',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
