# Generated by Django 2.2.2 on 2019-07-01 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_auto_20190701_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='a',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='column2',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='column3',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='column4',
        ),
        migrations.AddField(
            model_name='notification',
            name='event_Dashin',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dashin'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_schl_day',
            field=models.DateTimeField(verbose_name='Annual School Day'),
        ),
    ]
