# Generated by Django 2.2.2 on 2019-07-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0007_auto_20190701_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Not_carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_post', models.CharField(max_length=200)),
                ('carrier_subjct', models.CharField(max_length=200)),
                ('carrier_required', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Not_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_schl_day', models.DateTimeField(verbose_name='Annual School Day from')),
                ('to', models.DateTimeField()),
                ('saraswati_pooja', models.DateTimeField(verbose_name='Saraswati Pooja')),
            ],
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
