# Generated by Django 2.2.2 on 2019-07-01 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0008_auto_20190701_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='not_carrier',
            old_name='carrier_required',
            new_name='required',
        ),
    ]
