# Generated by Django 2.2.2 on 2019-07-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0009_auto_20190701_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Not_exams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slc', models.DateTimeField()),
                ('Eleven', models.DateTimeField()),
                ('Twelve', models.DateTimeField()),
            ],
        ),
    ]
