# Generated by Django 2.2.2 on 2019-07-01 06:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0012_auto_20190701_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='Send_up',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
