# Generated by Django 2.2.2 on 2019-07-01 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0015_auto_20190701_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='Eleven',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='Send_up',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='Twelve',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='slc',
        ),
        migrations.AddField(
            model_name='exam',
            name='Exam_for',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
